# Generated by Django 4.1.4 on 2022-12-15 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pahlawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('deskripsi', models.CharField(max_length=100)),
                ('tahun_lahir', models.TextField()),
                ('tahun_wafat', models.DateTimeField(auto_now_add=True)),
                ('tahun_jabatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barang.kategori')),
            ],
        ),
    ]